metaplex-foundation/solita

src/instruction-discriminator.ts
src/render-account.ts
src/render-instruction.ts
src/serdes.ts
src/solita.ts
src/type-mapper.ts
src/types.ts
src/utils.ts
test/anchor-examples/basic-0/.ammanrc.js
test/anchor-examples/basic-1/.ammanrc.js
test/anchor-examples/basic-2/.ammanrc.js
test/anchor-examples/basic-3/.ammanrc.js
test/anchor-examples/basic-4/.ammanrc.js
test/integration/fixtures/shank_tictactoe.json
test/integration/shank-tictactoe.ts
test/render-accounts.ts

Anchor implicitly works with instruction and account discriminators that are derived from their
name. This is not the case for plain contracts and thus for the ones whose IDL was extracted
via _shank_ we cannot assume that.
Instead shank provides discriminator information for each instruction (either the variant slot
or a value specified explicitly). For accounts no discriminator is assumed, but can be provided
via a `key` property which then works like any other account field.
Solita assumes no _magic_ discriminators for IDL whose `metadata.origin === 'shank'`.
It now generates correct code for these cases without breaking compatibility with _anchor_ IDL.
Additionally instruction accounts extracted via _shank_ can have a `desc` property which is
included as a comment.
`.ammanrc`s were …

feat: support shank IDL

---

src/known-pubkeys.ts
src/render-account.ts
src/render-instruction.ts
src/render-type.ts
src/serdes.ts
src/solita.ts
src/type-mapper.ts
test/anchor-examples/basic-1/test/initialize-and-update.ts
test/anchor-examples/basic-2/test/create-and-increment.ts
test/anchor-examples/basic-3/test/create-and-pull.ts
test/anchor-examples/basic-4/test/emitting-errors.ts
test/integration/fixtures/shank_token_vault.json
test/integration/shank-token-vault.ts
test/render-accounts.ts
test/render-instruction.ts
test/type-mapper.ts

This PR contains the following fixes and improvements applied while using solita in a few
scenarios:
- types: simplified naming of enum/struct beets
- code: rendering main index file that reesports all generated folders
- ix: including instruction account attributes in comment
- ix: accounts docs don't include known pubkeys
- accounts: allow them to be imported via `defined` like types

chore: fixes and improvements while integrating

---

src/render-type.ts
src/solita.ts
test/integration/fixtures/shank_token_metadata.json
test/integration/shank-token-metadata.ts
test/render-type.ts

In some cases types that needed to be _fixable_ due to one of it's field's types being
_fixable_ were not correctly detected as such.
This PR introduces a 2-pass strategy to first determine if a type needs to be fixable due to
its _known_ field types and then uses that information in the render pass in order to determine
if one of those is a _child_ of another type to then mark that parent _fixable_ as well.
The token-metadata IDL is now included in integration tests and I added checks to specifically
verify that _dependent on fixable_ types are marked as _fixable_ themselves.
Additionally I generated the token-metadata code inside the mpl repo from scratch and was able
to build + run tests without any edits to that code.

fix: fixable types not properly bubbling

---

src/render-instruction.ts
src/types.ts
test/integration/fixtures/shank_token_metadata.json
test/render-instruction.ts

Considers instruction accounts that have `option: true` configured in the IDL special.
Given `useAuthorityRecord` and `burner` are optional the generated code will first create the
required accounts meta array (`keys`) and then add code similar to the below:
```ts
if (useAuthorityRecord != null) {
keys.push({
pubkey: useAuthorityRecord,
isWritable: true,
isSigner: false,
})
}
if (burner != null) {
if (useAuthorityRecord == null) {
throw new Error(
"When providing 'burner' then 'useAuthorityRecord' need(s) to be provided as well."
)
}
keys.push({
pubkey: burner,
isWritable: false,
isSigner: false,
})
}
```
NOTE: that it also ensures that for consecutive _optional_ accounts the previous accounts all
need to be supplied.
FIXES: #25

feat: support optional instruction accounts

---

.github/workflows/solita.yml
package.json
src/render-instruction.ts
src/render-type.ts
test/anchor-examples/basic-0/programs/basic-0/src/lib.rs
test/anchor-examples/basic-0/test/initialize.ts
test/integration/auction-house-1.1.4-anchor-0.24.2.ts
test/integration/auction-house.ts
test/integration/fanout.ts
test/integration/fixtures/issue-empty-accounts.json
test/integration/fixtures/issue-missing-beet-import.json
test/integration/gumdrop.ts
test/integration/issue-empty-accounts.ts
test/integration/issue-missing-beet-import.ts
test/integration/nft-candy-machine-v1.ts
test/integration/shank-tictactoe.ts
test/integration/shank-token-metadata.ts
test/integration/shank-token-vault.ts
test/utils/tsc.ts
test/utils/verify-code.ts

- test: adding missing beet import integration test
- chore: fix missing beet import
- test: showing empty ix accounts issue
- chore: handle empty ix accounts correclty
- chore: adding test util to typecheck code with tsc
- test: verifying with tsc for all existing tests
- basic-0: fix rust return type
- basic-0: adapt test to no longer needing empty account arg
- fixed in beet -> bumped it

chore: various fixes around types

---

src/render-account.ts
src/serdes.ts
src/solita.ts
src/types.ts
test/integration/feat-account-padding.ts
test/integration/fixtures/feat-account-padding.json
test/render-accounts.ts
test/render-instruction.ts

Renders accounts with a padded field in a manner that hides it from the user, but includes it
in de/serialization steps.
- accounts: exclude padded fields from account struct and args
- account: consider padding field in serialize method
- account: render padding as part of beet type
- test: different account padding scenarios
- fix: account for possibility of empty instructions
- test: adding account padding integration test
- [shank adding padding attribute](https://github.com/metaplex-foundation/shank/pull/25)
<details>
```ts
/**
* This code was GENERATED using the solita package.
* Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
*
* See: https://github.com/metaplex-foundation/solita
*/
import * as beet from …
```

feat: render padded account code

---

src/known-pubkeys.ts
src/render-instruction.ts
src/types.ts
test/render-instruction.ts

This PR adds the ability for users to do the following:
- provide a `programId`, if not provided it defaults to the `programId` provided to solita
during code generation
- provide overrides for _known_ account ids like `tokenProgram`, if not provided it defaults to
the keys provided by the respective libraries
_Auction Houes_ `buy` instruction serves as a shortened example of what is generated now:
```ts
/**
* Accounts required by the _buy_ instruction
*
* @property [**signer**] wallet
* @property [_writable_] paymentAccount
* @property [] transferAuthority
* @property [] treasuryMint
* @property [] tokenAccount
* @property [] metadata
* @property [_writable_] escrowPaymentAccount
* @property [] authority
* @property [] auctionHouse
* @property [_writable_] auctionHouseFeeAccount
* …
```

feat: override accound keys and program id

---

src/render-data-enum.ts
test/integration/fixtures/mpl_token_metadata.json
test/integration/mpl_token_metadata.ts

- test: mpl_token_metadata showing collection details data enum type issue
- fix: accounting for the fact that data enums are always fixable

fix: casting data enums to fixable beet

---

package.json
src/render-data-enum.ts
src/type-mapper.ts
src/types.ts
test/integration/feat-tuples.ts
test/integration/fixtures/feat-tuples.json
test/type-mapper.ts
test/utils/helpers.ts

Renders tuples (indicated via `tuple` in the IDL).
This supports tuples nested inside other types as in the below example as well as tuples whose
elements themselves are composites.
A part of nft-packs IDL was included to serve as a smoke-test and more detailed tests were
added to the typemapper.
Rendering `Vec<u32, u32, u32>`
```ts
export type PackConfig = {
weights: [number, number, number][]
}
export const packConfigBeet = new beet.FixableBeetArgsStruct<PackConfig>(
[
[
'weights',
beet.array(beet.fixedSizeTuple([beet.u32, beet.u32, beet.u32])),
],
],
'PackConfig'
)
```

feat: render tuples

---

package.json
src/render-data-enum.ts
src/solita.ts
src/transform-type.ts
src/type-mapper.ts
src/types.ts
src/utils/logs.ts
test/integration/feat-fix-anchor-maps.ts
test/integration/fixtures/feat-fix-anchor-maps.json

Anchor does not support map types like `HashMap` and thus treats them as user defined types
basically just copy/pasting the type from the Rust code, i.e. `HashMap<String,DataItem>`.
This PR adds a transformer function that runs _before_ types are processed. This transformer
tries to detect these cases and converts them to proper _map_ type definitions.
This won't work for 100% of the cases and thus is a stop gap for the cases we encounter for our
anchor programs.
Additionaly at this point it only transforms _fields_ for structs, i.e. if such an invalid map
definition is nested somehow, it will go undetected.
These limitations can be improved on with each new case we need to handle.
FIXES: #75

feat: fix anchor maps via transform

---

README.md
src/cli/gen-typescript.ts
src/cli/handlers.ts
src/cli/types.ts
src/render-instruction.ts
src/solita.ts
src/types.ts
test/render-instruction.ts

For anchor programs solita now renders an optional `anchorRemainingAccounts` property for the instruction
accounts, allowing users to specify them.
This can be turned off by setting `anchorRemainingAccounts = false` in the solita config.
Renders code outlined in [this
issue](https://github.com/metaplex-foundation/metaplex-program-library/issues/678) and thus fixes it.
```ts
export type ExecuteSaleInstructionAccounts = {
buyer: web3.PublicKey
seller: web3.PublicKey
tokenAccount: web3.PublicKey
tokenMint: web3.PublicKey
[ .. many more .. ]
programAsSigner: web3.PublicKey
rent?: web3.PublicKey
anchorRemainingAccounts?: web3.AccountMeta[]
}
[ .. ]
export function createExecuteSaleInstruction(
accounts: ExecuteSaleInstructionAccounts,
args: ExecuteSaleInstructionArgs,
programId = new …
```

feat: anchor remaining accounts

---

package.json
src/render-instruction.ts
test/render-instruction.ts

The intent of this PR was to just handle the case of empty accounts when we try to add
`anchorRemainingAccounts`. In this case we just assume that there are none and thus don't
render any of the code allowing users to add them.
If this assumption was wrong we need to iterate on this solution.
As a side effect I ran into issues with web3.js (missing cross-fetch) which originated from it
being a dep of beet-solita.
Thus after [upgrading numerous deps in the beet
repo](https://github.com/metaplex-foundation/beet/pull/42) we updated the beet deps here to
pull in those patches.

fix: handling empty accounts for anchor remaining accounts

---

package.json
src/type-mapper.ts
src/types.ts
test/integration/features.ts
test/integration/fixtures/feat-sets.json

Solita now renders code for `hashSet` and `bTreeSet` similarly to how was done for maps
https://github.com/metaplex-foundation/solita/pull/73.
An integration test with set samples was included.
Related shank PR: https://github.com/metaplex-foundation/shank/pull/38

feat: support sets

---

src/render-account.ts

The accounts method `fromAccountAddress` now supports a `commitment` parameter to be specified.
Fixes: #84
```ts
static async fromAccountAddress(
connection: web3.Connection,
address: web3.PublicKey,
commitmentOrConfig?: web3.Commitment | web3.GetAccountInfoConfig
): Promise<MasterEditionV1> {
const accountInfo = await connection.getAccountInfo(
address,
commitmentOrConfig
)
if (accountInfo == null) {
throw new Error(`Unable to find MasterEditionV1 account at ${address}`)
}
return MasterEditionV1.fromAccountInfo(accountInfo, 0)[0]
}
```

feat: accounts api fromAccounts improvement

---

package.json
src/cli/handlers.ts
src/cli/solita.ts
src/cli/types.ts

Previously solita failed to properly propagate exit codes of the tool generating the IDL. This
led to developers not being aware of the issue as well as the CI checking for IDL changes not
alerting either since in those cases solita just kept the old IDL and generated code from it.
This has been fixed as follows:
- non-zero exit codes of the handler tool, i.e. anchor are now propagated and solita will exit
with it to also return a non-zero exit code
- if an `Error:` is encountered in the `stderr` output of the handler tool then solita will
color it red to draw attention.
- the message alerting the user that something went wrong is also colored red
To further eliminate the possibility of the IDL generation failing without solita noticing I
will add an option to delete the existing IDL …

feat: better errors when IDL handler fails

---

src/cli/solita.ts
src/cli/types.ts
src/utils/index.ts

Adds onto #90 to make it less likely that a failure to generate the IDL file goes unnoticed.
FIXES: #89

feat: optionally removing existing IDL file before running

---

package.json
src/render-instruction.ts
src/transform-type.ts
src/types.ts
test/integration/contracts.ts
test/integration/features.ts
test/integration/fixtures/anchor-optional.json
test/integration/fixtures/feat-optional-accounts.json
test/render-instruction.ts

This PR adds support for "Anchor-style" optional accounts. The addition to the `IdlInstruction` type is a placeholder for now.

Feat: programId replacement style optional accounts

---

.gitignore
src/render-instruction.ts
test/render-instruction.ts

The current behaviour, when rendering the AccountMetas of an instruction, is to render all required accounts first and then the optional ones if any. If any required accounts are added after optional accounts, Solita will throw an error and fail to generate a library.
The issue with this approach is that some instructions may want to add required accounts after optional accounts to minimize breaking changes which is currently the case for one instruction of the Token Metadata program.
This PR solves this by allowing required accounts to be pushed to the `keys` array after optional accounts if any. The logic is as follows:
- It will first render the account array using all required accounts that appear before the first optional one.
- Then for every account after that, it will push that …

Allow required accounts after optional accounts when rendering instruction keys

---

src/render-data-enum.ts

This PR aims to make the type of generated `dataEnum` slightly stricter by providing the second type parameter of `Beet<T, V>`.
When type `V` is missing, it defaults to `Partial<T>` which makes little sense in the case of a `dataEnum` since we've got to provide the `__kind` in order to know how to serialise it.
This causes issues when using `dataEnum` types in other types such as the `map` type which expect both its keys and values to be of type `Beet<K, K>` and `Beet<V, V>` respectively.
Here's an example.
```ts
export const payloadTypeBeet = beet.dataEnum<PayloadTypeRecord>([
// ...
]) as beet.FixableBeet<PayloadType>;
```
When used in a map type, it throws a TypeError.
```ts
export const payloadBeet = new beet.FixableBeetArgsStruct<Payload>(
[['map', beet.map(payloadKeyBeet, …
```

Fix dataEnum cast

---

src/render-instruction.ts
src/types.ts

Anchor labels optional instruction accounts using the `isOptional` attribute whereas Solita expects the `optional` attribute as Shank uses the latter.
Support both `optional` and `isOptional` attributes to label optional instruction accounts.

Add support for isOptional instruction account attribute

---

src/render-instruction.ts
src/types.ts
test/render-instruction.ts

As the new shank version will assume.
This is a breaking change so the library should be bumped accordingly.

Default optional account strategy to program ID

---

src/cli/handlers.ts
src/cli/types.ts
test/anchor-examples/basic-0/.solitarc.js
test/anchor-examples/basic-0/idl/basic_0.json
test/anchor-examples/basic-0/programs/basic-0/Cargo.toml
test/anchor-examples/basic-1/idl/basic_1.json
test/anchor-examples/basic-1/programs/basic-1/Cargo.toml
test/anchor-examples/basic-2/idl/basic_2.json
test/anchor-examples/basic-2/programs/basic-2/Cargo.toml
test/anchor-examples/basic-3/programs/puppet-master/Cargo.toml
test/anchor-examples/basic-3/programs/puppet/Cargo.toml
test/anchor-examples/basic-4/idl/basic_4.json
test/anchor-examples/basic-4/programs/basic-4/Cargo.toml

This PR adds a `binaryArgs` property to `SolitaConfigBase` to allow configuring command-line arguments for the IDL generator.

Add binaryArgs field
